n = input('Digite um número: ')
print(n)
print(type(n))
print(n.isnumeric()) #Mostra se a variável for números (False ou True)
print(n.isalpha()) #Mostra se a variável for alguma letra (False ou True)
print(n.isalnum()) #Mostra se a variável possui letras e/ou números (False ou True)
print(n.isupper()) #Mostra se a variável possui somente letras maiúsculas (False ou True)
print(n.islower()) #Mostra se a variável possui somente letras minúsculas (False ou True)
print(n.isascii()) #Mostra se a variável possui caracteres ASCII (False ou True)
print(n.isdecimal()) #Mostra se a variável é decimal (False ou True)
